-- AlterTable
ALTER TABLE "SystemConfig"
ADD COLUMN "smallBoxCapacity" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "mediumBoxCapacity" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "largeBoxCapacity" INTEGER NOT NULL DEFAULT 40,
ADD COLUMN "customBoxCapacity" INTEGER NOT NULL DEFAULT 30;
