export type { IsraelShipmentRecord, IsraelShipmentStatus } from '../../../services/israel/israelShipmentsApi';
export type { IsraelBoxRecord, IsraelBoxStatus } from '../../../services/israel/israelBoxesApi';
export type { IsraelShipmentItemRecord } from '../../../services/israel/israelShipmentItemsApi';
export type { IsraelPitamStatus } from '../../../services/israel/israelClassificationsApi';

export type IsraelAllShipmentsTableLabels = {
  description: string;
  seasonFilterLabel: string;
  statusFilterLabel: string;
  allStatusesOption: string;
  fieldFilterLabel: string;
  allFieldsOption: string;
  activeSeasonBadge: string;
  noActiveSeason: string;
  colDetails: string;
  colShipmentNumber: string;
  colField: string;
  colBoxCount: string;
  colQuantity: string;
  colStatus: string;
  colShippedAt: string;
  detailsButtonAriaLabel: string;
  detailsPanelTitle: (shipmentNumber?: number) => string;
  detailsPanelCloseLabel: string;
  detailsUpdatedByLabel: string;
  detailsNotesLabel: string;
  detailsPrintLabel: string;
  detailsItemsLoading: string;
  detailsItemsEmpty: string;
  detailsItemsError: string;
  detailsItemsTable: {
    title: string;
    colBoxNumber: string;
    colCategory: string;
    colGrade: string;
    colPitamStatus: string;
    colQuantity: string;
    colNotes: string;
    uncategorized: string;
    noGrade: string;
    pitamStatusLabels: Record<'WITH_PITAM' | 'WITHOUT_PITAM' | 'MIXED', string>;
  };
  empty: string;
  loading: string;
  error: string;
  summary: {
    totalShipments: string;
    totalBoxes: string;
    totalQuantity: string;
  };
  statusLabels: Record<import('../../../services/israel/israelShipmentsApi').IsraelShipmentStatus, string>;
  tableActionsLabel: string;
  tablePrintTitle: string;
  tablePrintAriaLabel: string;
  tableExportTitle: string;
  tableExportAriaLabel: string;
  tableExportError: string;
};

export type IsraelBoxesTableRow = {
  id: number;
  boxNumber: number;
  fieldId: number;
  fieldName: string;
  shipmentNumber: number | null;
  itemsCount: number;
  status: import('../../../services/israel/israelBoxesApi').IsraelBoxStatus;
  updatedByName: string;
  notes: string | null;
};

export type IsraelAllBoxesTableLabels = {
  description: string;
  seasonFilterLabel: string;
  shipmentNumberFilterLabel: string;
  boxNumberFilterLabel: string;
  boxNumberFilterPlaceholder: string;
  boxStatusFilterLabel: string;
  fieldFilterLabel: string;
  allFieldsOption: string;
  allShipmentNumbersOption: string;
  unassignedShipmentOption: string;
  allBoxStatusesOption: string;
  activeSeasonBadge: string;
  noActiveSeason: string;
  colDetails: string;
  colBoxNumber: string;
  colField: string;
  colShipmentNumber: string;
  colItemsCount: string;
  colStatus: string;
  selectRowAriaLabel: string;
  detailsButtonAriaLabel: string;
  detailsPanelTitle: (boxNumber?: number) => string;
  detailsPanelCloseLabel: string;
  detailsUpdatedByLabel: string;
  detailsNotesLabel: string;
  detailsPrintLabel: string;
  detailsItemsLoading: string;
  detailsItemsEmpty: string;
  detailsItemsError: string;
  detailsItemsTable: {
    title: string;
    colBoxNumber: string;
    colCategory: string;
    colGrade: string;
    colPitamStatus: string;
    colQuantity: string;
    colNotes: string;
    uncategorized: string;
    noGrade: string;
    pitamStatusLabels: Record<'WITH_PITAM' | 'WITHOUT_PITAM' | 'MIXED', string>;
  };
  unassignedShipmentLabel: string;
  empty: string;
  loading: string;
  error: string;
  summary: {
    totalBoxes: string;
    notShipped: string;
    shipped: string;
  };
  statusLabels: Record<import('../../../services/israel/israelBoxesApi').IsraelBoxStatus, string>;
  tableActionsLabel: string;
  tablePrintTitle: string;
  tablePrintAriaLabel: string;
  tableExportTitle: string;
  tableExportAriaLabel: string;
  tableExportError: string;
};

export type IsraelShipmentItemsTableRow = {
  id: number;
  boxId: number;
  boxNumber: number;
  fieldId: number | null;
  shipmentNumber: number | null;
  categoryId: number;
  category: string;
  grade: string;
  pitamStatus: import('../../../services/israel/israelClassificationsApi').IsraelPitamStatus;
  quantity: number;
  notes: string | null;
  updatedByName: string;
};

export type IsraelFieldShipmentItemsTableRow = {
  id: number;
  boxId: number;
  boxNumber: number;
  fieldId: number | null;
  shipmentNumber: number | null;
  shipmentStatus: import('../../../services/israel/israelShipmentsApi').IsraelShipmentStatus | null;
  categoryId: number;
  category: string;
  grade: string;
  pitamStatus: import('../../../services/israel/israelClassificationsApi').IsraelPitamStatus;
  quantity: number;
};

export type IsraelFieldShipmentItemsTableLabels = {
  description: string;
  seasonFilterLabel: string;
  shipmentNumberFilterLabel: string;
  allShipmentNumbersOption: string;
  fieldFilterLabel: string;
  allFieldsOption: string;
  shipmentStatusFilterLabel: string;
  allShipmentStatusesOption: string;
  shipmentStatusLabels: Record<import('../../../services/israel/israelShipmentsApi').IsraelShipmentStatus, string>;
  activeSeasonBadge: string;
  noActiveSeason: string;
  colCategory: string;
  noGrade: string;
  pitamStatusLabels: Record<'WITH_PITAM' | 'WITHOUT_PITAM' | 'MIXED', string>;
  empty: string;
  loading: string;
  error: string;
  summary: {
    totalShipments: string;
    totalBoxes: string;
    totalQuantity: string;
    total: string;
  };
};

export type IsraelShipmentItemsSummaryTableLabels = {
  description: string;
  seasonFilterLabel: string;
  activeSeasonBadge: string;
  noActiveSeason: string;
  colShipmentNumber: string;
  colField: string;
  colBoxCount: string;
  colQuantity: string;
  colStatus: string;
  empty: string;
  loading: string;
  error: string;
  summary: {
    totalShipments: string;
    totalBoxes: string;
    totalQuantity: string;
  };
  statusLabels: Record<import('../../../services/israel/israelShipmentsApi').IsraelShipmentStatus, string>;
  fieldCategoryMatrix: {
    title: string;
    fieldColumn: string;
    totalQuantityColumn: string;
    totalBoxesColumn: string;
    grandTotalLabel: string;
    empty: string;
  };
};

export type IsraelShipmentItemsTableLabels = {
  description: string;
  seasonFilterLabel: string;
  boxNumberFilterLabel: string;
  shipmentNumberFilterLabel: string;
  allBoxNumbersOption: string;
  allShipmentNumbersOption: string;
  fieldFilterLabel: string;
  allFieldsOption: string;
  activeSeasonBadge: string;
  noActiveSeason: string;
  colDetails: string;
  colBoxNumber: string;
  colField: string;
  colShipmentNumber: string;
  colCategory: string;
  colGrade: string;
  colPitamStatus: string;
  colQuantity: string;
  detailsButtonAriaLabel: string;
  detailsPanelTitle: (id?: number) => string;
  detailsPanelCloseLabel: string;
  detailsUpdatedByLabel: string;
  detailsNotesLabel: string;
  detailsPrintLabel: string;
  pitamStatusLabels: Record<'WITH_PITAM' | 'WITHOUT_PITAM' | 'MIXED', string>;
  unassignedShipmentLabel: string;
  empty: string;
  loading: string;
  error: string;
  summary: {
    totalItems: string;
    totalQuantity: string;
  };
  tableActionsLabel: string;
  tablePrintTitle: string;
  tablePrintAriaLabel: string;
  tableExportTitle: string;
  tableExportAriaLabel: string;
  tableExportError: string;
};
