import type { ShipmentStatus } from '../../services/shipmentsApi';
import type { BoxOwnership, BoxStatus } from '../../services/boxesApi';
import type { ItemOwnership, GeneralSourceBreakdownEntry } from '../../services/shipmentItemsApi';

export type { ItemOwnership };

export type { ShipmentRecord } from '../../services/shipmentsApi';
export type { ShipmentStatus };

export type BoxesTableRow = {
  id: number;
  boxNumber: number;
  shipmentNumber: number;
  boxType: string;
  totalQuantity: number;
  status: BoxStatus;
  ownership: string;
  updatedByName: string;
  notes: string | null;
};

export type ShipmentItemsTableRow = {
  id: number;
  boxId: number;
  boxNumber: number;
  shipmentNumber: number;
  category: string;
  quantity: number;
  ownership: string;
  ownershipType: ItemOwnership;
  isPrivateSelection: boolean;
  grade: string | null;
  customGrade: string | null;
  pitamStatus: string | null;
  notes: string | null;
  updatedByName: string;
  generalSourceBreakdown: GeneralSourceBreakdownEntry[] | null;
};

export type ShipmentsTableLabels = {
  title: string;
  description: string;
  seasonFilterLabel: string;
  statusFilterLabel: string;
  allStatusesOption: string;
  activeSeasonBadge: string;
  noActiveSeason: string;
  colDetails: string;
  colShipmentNumber: string;
  colBoxCount: string;
  colQuantity: string;
  colStatus: string;
  colShippedAt: string;
  detailsButtonAriaLabel: string;
  detailsPanelTitle: (shipmentNumber?: number) => string;
  detailsPanelCloseLabel: string;
  detailsPrintLabel: string;
  detailsUpdatedByLabel: string;
  detailsNotesLabel: string;
  detailsBoxesSummary: {
    title: string;
    boxTypeLabels: Record<'SMALL' | 'MEDIUM' | 'LARGE' | 'CUSTOM', string>;
    generalRowLabel: string;
    customRowLabel: string;
    totalRowLabel: string;
    totalColumnLabel: string;
    loading: string;
    error: string;
    empty: string;
  };
  detailsEtrogSummary: {
    title: string;
    pitamStatusLabels: Record<'WITH_PITAM' | 'WITHOUT_PITAM' | 'MIXED', string>;
    customRowLabel: string;
    totalRowLabel: string;
    totalColumnLabel: string;
    loading: string;
    error: string;
    empty: string;
  };
  detailsItemsTable: {
    title: string;
    colBoxNumber: string;
    colOwnership: string;
    colStockSource: string;
    colCategory: string;
    colGrade: string;
    colQuantity: string;
    colNotes: string;
    colGeneralSourceBreakdown: string;
    generalSourceModuloLabel: string;
    ownershipLabels: Record<'TRADER' | 'CUSTOMER' | 'GENERAL' | 'CUSTOM', string>;
    stockSourceLabels: Record<'GENERAL' | 'PRIVATE_SELECTION', string>;
    uncategorized: string;
    noGrade: string;
  };
  empty: string;
  loading: string;
  error: string;
  summary: {
    totalShipments: string;
    totalBoxes: string;
    totalQuantity: string;
  };
  statusLabels: Record<ShipmentStatus, string>;
};

export type BoxesTableLabels = {
  title: string;
  description: string;
  seasonFilterLabel: string;
  shipmentNumberFilterLabel: string;
  boxStatusFilterLabel: string;
  ownershipFilterLabel: string;
  allShipmentNumbersOption: string;
  allBoxStatusesOption: string;
  allOwnershipOption: string;
  allTradersOption: string;
  allCustomersOption: string;
  activeSeasonBadge: string;
  noActiveSeason: string;
  colDetails: string;
  colBoxNumber: string;
  colShipmentNumber: string;
  colBoxType: string;
  colQuantity: string;
  colStatus: string;
  colOwnership: string;
  boxTypeLabels: Record<string, string>;
  detailsButtonAriaLabel: string;
  detailsPanelTitle: (boxNumber?: number) => string;
  detailsPanelCloseLabel: string;
  detailsPrintLabel: string;
  detailsUpdatedByLabel: string;
  detailsNotesLabel: string;
  detailsItemsTable: ShipmentsTableLabels['detailsItemsTable'];
  detailsItemsLoading: string;
  detailsItemsError: string;
  detailsItemsEmpty: string;
  empty: string;
  loading: string;
  error: string;
  summary: {
    totalBoxes: string;
    notShipped: string;
    shipped: string;
  };
  statusLabels: Record<BoxStatus, string>;
  ownershipLabels: Record<BoxOwnership, string>;
};

export type ShipmentItemsTableLabels = {
  title: string;
  description: string;
  seasonFilterLabel: string;
  boxNumberFilterLabel: string;
  shipmentNumberFilterLabel: string;
  ownershipFilterLabel: string;
  allBoxNumbersOption: string;
  allShipmentNumbersOption: string;
  allOwnershipOption: string;
  allTradersOption: string;
  allCustomersOption: string;
  tradersGroupLabel: string;
  customersGroupLabel: string;
  activeSeasonBadge: string;
  noActiveSeason: string;
  colDetails: string;
  colBoxNumber: string;
  colShipmentNumber: string;
  colCategory: string;
  colQuantity: string;
  colOwnership: string;
  colStockSource: string;
  stockSourceLabels: { GENERAL: string; PRIVATE_SELECTION: string };
  detailsButtonAriaLabel: string;
  detailsPanelTitle: (itemId?: number) => string;
  detailsPanelCloseLabel: string;
  detailsPrintLabel: string;
  detailsUpdatedByLabel: string;
  detailsNotesLabel: string;
  detailsGeneralSourceTitle: string;
  detailsGeneralSourceModuloLabel: string;
  colGrade: string;
  colPitamStatus: string;
  pitamStatusLabels: Record<string, string>;
  noGrade: string;
  noPitamStatus: string;
  uncategorized: string;
  empty: string;
  loading: string;
  error: string;
  summary: {
    totalShipments: string;
    totalBoxes: string;
    totalQuantity: string;
    generalQuantity: string;
    privateSelectionQuantity: string;
    traderAndGeneralQuantity: string;
    customerQuantity: string;
    total: string;
  };
  summaryMatrix: {
    title: string;
    categoriesTitle: string;
    privateSelectionTitle: string;
    customersTitle: string;
    showBreakdown: string;
    hideBreakdown: string;
    typeColumnLabel: string;
    privateSelectionLabel: string;
    customersLabel: string;
    grandTotalLabel: string;
  };
  perShipmentTable: {
    title: string;
    rowBoxes: string;
    rowStatus: string;
    statusLabels: Record<ShipmentStatus, string>;
  };
  ownershipLabels: Record<ItemOwnership, string>;
};
